# Generated by Django 2.2.4 on 2021-02-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows', '0003_auto_20210220_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
    ]
