# Generated by Django 2.2.4 on 2021-02-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='item',
        ),
    ]
