# Generated by Django 2.2.4 on 2021-02-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
