# Generated by Django 2.2.4 on 2021-02-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_application', '0002_authors_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
