# Generated by Django 2.2.4 on 2021-02-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utemp', '0002_auto_20210216_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='userage',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='useremail',
        ),
        migrations.AddField(
            model_name='user',
            name='userfirst',
            field=models.CharField(default='bob', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userlast',
            field=models.CharField(default='sally', max_length=255),
            preserve_default=False,
        ),
    ]
