# Generated by Django 2.2.4 on 2021-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(),
        ),
    ]
