# Generated by Django 2.2.4 on 2021-03-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carInfo', '0002_auto_20210303_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='note',
            field=models.TextField(default='clean title'),
            preserve_default=False,
        ),
    ]
